/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IsotopicMightyGamers;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Poindexter
 */
public class Business extends javax.swing.JFrame {
    
    public static int purchases;
    public static int sales;

    /**
     * Creates new form Business
     */
    public Business() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        pnlTop.setOpaque(true);
        pnlTop.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selling3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlTop = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        GrossProfit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bestBrand = new javax.swing.JTextField();
        expertEmp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bestprod = new javax.swing.JTextField();
        bestcust = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        revenue = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        selling = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buycost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buying = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        To = new com.toedter.calendar.JDateChooser();
        From = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        selling3.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        selling3.setForeground(new java.awt.Color(0, 51, 51));
        selling3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        selling3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selling3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Back");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 780, 120, 50));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Enter");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 130, -1));

        pnlTop.setBackground(new java.awt.Color(0, 51, 153));
        pnlTop.setPreferredSize(new java.awt.Dimension(1024, 30));
        pnlTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopMouseDragged(evt);
            }
        });
        pnlTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTopMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopMousePressed(evt);
            }
        });
        pnlTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton6.setText("-");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnlTop.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 50, -1));

        jButton9.setBackground(new java.awt.Color(255, 51, 51));
        jButton9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 204, 204));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pnlTop.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 50, -1));

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 50));

        jLabel13.setFont(new java.awt.Font("Cambria", 3, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gross Profit");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 690, 180, 40));

        GrossProfit.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        GrossProfit.setForeground(new java.awt.Color(0, 51, 51));
        GrossProfit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GrossProfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrossProfitActionPerformed(evt);
            }
        });
        getContentPane().add(GrossProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 690, 450, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Best Brand");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 180, 40));

        bestBrand.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bestBrand.setForeground(new java.awt.Color(0, 51, 51));
        bestBrand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bestBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestBrandActionPerformed(evt);
            }
        });
        getContentPane().add(bestBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, 270, 30));

        expertEmp.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        expertEmp.setForeground(new java.awt.Color(0, 51, 51));
        expertEmp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expertEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expertEmpActionPerformed(evt);
            }
        });
        getContentPane().add(expertEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 270, 30));

        jLabel11.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Expert Employee");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 180, 40));

        jLabel10.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Best Product");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 180, 40));

        bestprod.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bestprod.setForeground(new java.awt.Color(0, 51, 51));
        bestprod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bestprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestprodActionPerformed(evt);
            }
        });
        getContentPane().add(bestprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 270, 30));

        bestcust.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        bestcust.setForeground(new java.awt.Color(0, 51, 51));
        bestcust.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bestcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestcustActionPerformed(evt);
            }
        });
        getContentPane().add(bestcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 270, 30));

        jLabel9.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Loyal Customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 180, 40));

        revenue.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        revenue.setForeground(new java.awt.Color(0, 51, 51));
        revenue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        revenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueActionPerformed(evt);
            }
        });
        getContentPane().add(revenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 270, 30));

        jLabel8.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Revenue");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 110, 40));

        selling.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        selling.setForeground(new java.awt.Color(0, 51, 51));
        selling.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        selling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingActionPerformed(evt);
            }
        });
        getContentPane().add(selling, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 270, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Number of Sales");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 180, 40));

        jLabel6.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Purchase Cost");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 180, 40));

        buycost.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        buycost.setForeground(new java.awt.Color(0, 51, 51));
        buycost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buycost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buycostActionPerformed(evt);
            }
        });
        getContentPane().add(buycost, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 270, 30));

        jLabel5.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number of purchases");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 180, 40));

        buying.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        buying.setForeground(new java.awt.Color(0, 51, 51));
        buying.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyingActionPerformed(evt);
            }
        });
        getContentPane().add(buying, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 270, 30));

        jLabel4.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 60, 40));

        jLabel3.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 60, 40));
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 230, 30));
        getContentPane().add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 230, 30));

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Business Information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 660, 110));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IsotopicMightyGamers/Info.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    int xx,xy;
    private void buyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyingActionPerformed

    private void buycostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buycostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buycostActionPerformed

    private void sellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellingActionPerformed

    private void revenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revenueActionPerformed

    private void bestcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestcustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestcustActionPerformed

    private void selling3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selling3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selling3ActionPerformed

    private void bestprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestprodActionPerformed

    private void expertEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expertEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expertEmpActionPerformed

    private void bestBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestBrandActionPerformed

    private void GrossProfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrossProfitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrossProfitActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setState(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to quit?","EXIT",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void pnlTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTopMouseDragged

    private void pnlTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (Business.this.getExtendedState() == MAXIMIZED_BOTH) {
                Business.this.setExtendedState(JFrame.NORMAL);
            } else {
                Business.this.setExtendedState(MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_pnlTopMouseClicked

    private void pnlTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTopMousePressed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        try{
           
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           String url = "jdbc:sqlserver://localhost:1433;databaseName=MacroGameZone;user=sa;password=p@ssword13";
           
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           String Fr = sdf.format(From.getDate());
           String FrDate = "'"+Fr+"'";
           String T = sdf.format(To.getDate());
           String TDate = "'"+T+"'";
           
           String query1 = "select count(Product_ID) as 'Purchased Items' from Product where Shipping_Date >= "+FrDate+" and Shipping_Date <= "+TDate+" ";
           String query2 = "select SUM(PurchaseCost) as 'Cost of purchases' from Product where Shipping_Date >= "+FrDate+" and Shipping_Date <= "+TDate+" ";
           String query3 = "select count(Orders.Customer_ID) as 'Total Sales' from Customer Right Join Orders on Customer.Customer_ID = Orders.Customer_ID where Order_Date >= "+FrDate+" and Order_Date <= "+TDate+" ";
           String query4 = "select SUM(Price) from Orders Right Join Customer on Orders.Customer_ID = Customer.Customer_ID Right Join Product  on Product.Product_ID = Orders.Product_ID where Order_Date >= "+FrDate+" and Order_Date <= "+TDate+" ";
           String query5 = "select  C_Name From Customer Right Join Orders on Customer.Customer_ID = Orders.Customer_ID Group by C_Name,Order_Date Having Order_Date >= "+FrDate+" and Order_Date <="+TDate+" order by count(Orders.Customer_ID) desc";
           String query6 = "select  Product_Name From Product Right Join Orders on Product.Product_ID = Orders.Product_ID Group by Product_Name,Order_Date having Order_Date >= "+FrDate+" and Order_Date <= "+TDate+"  order by count(Orders.Product_ID) desc";
           String query7 = "SELECT D_Name, CONVERT(int,ROUND(DATEDIFF(hour,JoiningDate,GETDATE())/8766.0,0)) AS 'Years worked' from DeliveryMan order by [Years Worked] desc";
           String query8 = "select Brand from Product Right Join Orders on Product.Product_ID = Orders.Product_ID Group by Brand,Order_Date having Order_Date >= "+FrDate+" and Order_Date <= "+TDate+" order by count(Product.Brand) desc";
           
           Connection con = DriverManager.getConnection(url);
           Statement st = con.createStatement();
           
           ResultSet rs = st.executeQuery(query1);
           
           if(rs.next())
            {
                buying.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No Purchases on the selected time timeline!");
            }
           
            rs = st.executeQuery(query2);
           
            if(rs.next())
            {
                buycost.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, 0);
            }
            
            try{
            purchases = Integer.parseInt(rs.getString(1));
            }catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(null, "No Purchases on the selected time timeline!");
                buycost.setText("0");
            }
            
            rs = st.executeQuery(query3);
           
            if(rs.next())
            {
                selling.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No sales on the selected timeline!");
            }
            
            rs = st.executeQuery(query4);
           
            if(rs.next())
            {
                revenue.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, 0);
            }
            
            
            try{
            sales = Integer.parseInt(rs.getString(1));
            }catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(null, "No sales on the selected timeline!");
                selling.setText("0");
                revenue.setText("0");
            }
            
            
            int ProfitorLoss = sales - purchases;
            String GP = String.valueOf(ProfitorLoss);
            GrossProfit.setText(GP);
            
            rs = st.executeQuery(query5);
           
            if(rs.next())
            {
                bestcust.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No customer found!");
            }
  
            rs = st.executeQuery(query6);
           
            if(rs.next())
            {
                bestprod.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Most selling product is not found on the selected timeline!");
            }
            
            rs = st.executeQuery(query7);
           
            if(rs.next())
            {
                expertEmp.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Most experience deliveryman is not found on the selected timeline!");
            }

            rs = st.executeQuery(query8);
           
            if(rs.next())
            {
                bestBrand.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Most selling brand is not found on the selected timeline!");
            }
                       
       }catch(NullPointerException ex)
       {
           JOptionPane.showMessageDialog(null, "Please enter a valid date!");
       }catch(ClassNotFoundException ex)
       {
           JOptionPane.showMessageDialog(null, ex);
       }catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null, ex);
       }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        Home H = new Home();
        H.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Business().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser From;
    private javax.swing.JTextField GrossProfit;
    private com.toedter.calendar.JDateChooser To;
    private javax.swing.JTextField bestBrand;
    private javax.swing.JTextField bestcust;
    private javax.swing.JTextField bestprod;
    private javax.swing.JTextField buycost;
    private javax.swing.JTextField buying;
    private javax.swing.JTextField expertEmp;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField revenue;
    private javax.swing.JTextField selling;
    private javax.swing.JTextField selling3;
    // End of variables declaration//GEN-END:variables
}
