/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IsotopicMightyGamers;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Poindexter
 */
public class InsertProduct extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    
    

    /**
     * Creates new form InsertProduct
     */
    public InsertProduct() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        pnlTop.setOpaque(true);
        pnlTop.setBackground(new Color(0,0,0,0));
    }

    int xx,xy;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Prod_ID = new javax.swing.JTextField();
        Prod_Name = new javax.swing.JTextField();
        Prod_Price = new javax.swing.JTextField();
        Prod_Warranty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Shipping_Date = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        B = new javax.swing.JComboBox();
        locat = new javax.swing.JComboBox();
        Costings = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        pnlTop = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(93, 173, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("Enter Product Detail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 343, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("ProductID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 153, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Product_Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 235, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Buying price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 380, 98, 34));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Brand");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 471, 98, 39));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Warranty");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 563, 98, 39));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Shipping_Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 636, -1, 58));

        Prod_ID.setForeground(new java.awt.Color(153, 153, 153));
        Prod_ID.setText("2000");
        Prod_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Prod_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Prod_IDFocusLost(evt);
            }
        });
        Prod_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prod_IDActionPerformed(evt);
            }
        });
        jPanel1.add(Prod_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 150, 324, 33));
        jPanel1.add(Prod_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 226, 324, 44));
        jPanel1.add(Prod_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 320, 324, 34));
        jPanel1.add(Prod_Warranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 567, 324, 34));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 624, -1, 70));
        jPanel1.add(Shipping_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 643, 227, 38));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Country");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 720, 114, 42));

        B.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        B.setForeground(new java.awt.Color(0, 51, 51));
        B.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sony", "Nintendo", "Microsoft", "Asus", "MSI", "Havit", "Astro", "Razer", " " }));
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        jPanel1.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 467, 324, 44));

        locat.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        locat.setForeground(new java.awt.Color(0, 51, 51));
        locat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "China", "Japan", "Australia", "Bangladesh", "Canada", "United States" }));
        jPanel1.add(locat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 719, 324, 43));
        jPanel1.add(Costings, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 380, 321, 34));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Selling Price");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 320, 98, 34));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Quantity");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 817, 114, 42));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 819, 328, 42));

        pnlTop.setBackground(new java.awt.Color(153, 204, 255));
        pnlTop.setPreferredSize(new java.awt.Dimension(1024, 30));
        pnlTop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopMouseDragged(evt);
            }
        });
        pnlTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTopMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopMousePressed(evt);
            }
        });
        pnlTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pnlTop.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 50, -1));

        jButton9.setBackground(new java.awt.Color(255, 51, 51));
        jButton9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 204, 204));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pnlTop.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 50, -1));

        jPanel1.add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Confirm");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 940, 120, 50));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Back");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 940, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Prod_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prod_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Prod_IDActionPerformed

    private void Prod_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Prod_IDFocusGained
        if(Prod_ID.getText().equals("2000"))
        {
            Prod_ID.setText("");
            Prod_ID.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Prod_IDFocusGained

    private void Prod_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Prod_IDFocusLost
       if(Prod_ID.getText().equals(""))
        {
            Prod_ID.setText("2000");
            Prod_ID.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Prod_IDFocusLost

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed

        
    }//GEN-LAST:event_BActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setState(1);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to quit?","EXIT",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void pnlTopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pnlTopMouseDragged

    private void pnlTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (InsertProduct.this.getExtendedState() == MAXIMIZED_BOTH) {
                InsertProduct.this.setExtendedState(JFrame.NORMAL);
            } else {
                InsertProduct.this.setExtendedState(MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_pnlTopMouseClicked

    private void pnlTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pnlTopMousePressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        try{
            String query = "INSERT INTO Product(Product_ID, Product_Name,Price,Brand,Warranty,Shipping_Date,Country,PurchaseCost,quantity) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=MacroGameZone;selectMethod=cursor", "sa", "p@ssword13");
            Statement St = con.createStatement();
             
            pst = con.prepareStatement(query);
            
            if(Prod_ID.getText().equals("2000"))
            {
                JOptionPane.showMessageDialog(null, "Product ID is missing!");
            }
            else if(Prod_ID.getText().charAt(0) != '2')
            {
                JOptionPane.showMessageDialog(null, "Product ID must follow the pattern 2###");
            }
            else
            {
                pst.setString(1, Prod_ID.getText());
            }
            if(Prod_Name.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Product name is missing!");
            }
            else
            {
                pst.setString(2, Prod_Name.getText());
            }
            
            if(Prod_Price.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Product price is missing!");
            }
            else
            {
                pst.setString(3, Prod_Price.getText());
            }
            
            String SV = B.getSelectedItem().toString();
            
            if(SV.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Brand name is missing!");
            }
            else
            {
                
                pst.setString(4,SV);
            }
            
            if(Prod_Warranty.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Warranty is missing!");
            }
            else
            {  
                pst.setString(5, Prod_Warranty.getText());
            }
            
                
            try{
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String deliveryDate = sdf.format(Shipping_Date.getDate());
                pst.setString(6, deliveryDate);
                
            }catch(NullPointerException ex)
            {
                JOptionPane.showMessageDialog(null, "Shipping date is missing!");
            }
            
            String location = locat.getSelectedItem().toString();
            
            if(location.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Shipping country is missing!");
            }
            else
            {  
                pst.setString(7,location);
            }
            
            if(Costings.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Buying price is missing!");
            }
            else
            {
                pst.setString(8, Costings.getText());
            }
            
            if(quantity.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Quantity is missing!");
            }
            else
            {
                pst.setString(9, quantity.getText());
            }

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "New Product has been added!!");

            Products obj = new Products();

            obj.setVisible(true);
            dispose();

        }catch(SQLException ex){
            
            int a = ex.getErrorCode();
            
            if(a == 2627)
            {
                JOptionPane.showMessageDialog(null, "A product with the same id exists in the database!");
            }
            
            else if(a == 0)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
            
            else
                JOptionPane.showMessageDialog(null, "Try Again!");
            
        } catch (Exception ex) {
            Logger.getLogger(InsertProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       Home H = new Home();
       H.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox B;
    private javax.swing.JTextField Costings;
    private javax.swing.JTextField Prod_ID;
    private javax.swing.JTextField Prod_Name;
    private javax.swing.JTextField Prod_Price;
    private javax.swing.JTextField Prod_Warranty;
    private com.toedter.calendar.JDateChooser Shipping_Date;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox locat;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
